pipeline:
  name: SimpleJavaTest
  identifier: SimpleJavaTest
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: POC-KALPESHY/SimpleJavaTest
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - stepGroup:
                  name: compile
                  identifier: compile
                  steps:
                    - step:
                        type: RunTests
                        name: Test
                        identifier: Test
                        spec:
                          language: Java
                          buildTool: Maven
                          args: clean test
                          runOnlySelectedTests: true
                          reports:
                            type: JUnit
                            spec:
                              paths:
                                - "**/*.xml"
                          enableTestSplitting: false
                    - step:
                        type: Run
                        name: Build
                        identifier: Build
                        spec:
                          shell: Sh
                          command: mvn package
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
