pipeline:
  name: SimpleJavaTest
  identifier: SimpleJavaTest
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: POC-KALPESHY/SimpleJavaTest
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - stepGroup:
                  name: compile
                  identifier: compile
                  steps:
                    - step:
                        type: RunTests
                        name: Test
                        identifier: Test
                        spec:
                          language: Java
                          buildTool: Maven
                          args: clean test
                          runOnlySelectedTests: true
                          reports:
                            type: JUnit
                            spec:
                              paths:
                                - "**/*.xml"
                          enableTestSplitting: false
                    - step:
                        type: Run
                        name: Build
                        identifier: Build
                        spec:
                          shell: Sh
                          command: mvn package
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: Sonarqube
                      name: Sonarqube
                      identifier: Sonarqube
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                          properties:
                            sonar.organization: poc-gitlab-ci-cd
                            sonar.projectKey: poc-gitlab-ci-cd_harness-simple-java-test
                        auth:
                          access_token: d9fae163680f0107cb09134b58665032059873f6
                          domain: https://sonarcloud.io
                          ssl: true
                  - step:
                      type: Semgrep
                      name: Semgrep_1
                      identifier: Semgrep_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                  - step:
                      type: Gitleaks
                      name: Gitleaks_1
                      identifier: Gitleaks_1
                      spec:
                        target:
                          detection: auto
                          type: repository
                        advanced:
                          log:
                            level: info
                          args:
                            cli: trivy
                        mode: orchestration
                        config: default
